### PR TITLE
fix: fix conflict between lease request and kv request

### LINKED ISSUE #303: [Bug]: Validation CI may block at lock validation test
### Description about the bug

Validation CI may block at lock validation test

### Version

0.4.0 (Default)

### Relevant log output

```shell
auth validation test running...
command run success
...
command run success
auth validation test passed
lock validation test running...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by themanforfree**
Close #303, #284

Please briefly answer these questions:

* what problem are you trying to solve? (or if there's no problem, what's the motivation for this change?)

* what changes does this pull request make?

* are there any non-obvious implications of these changes? (does it break compatibility with previous versions, etc)

### CODE REVIEW

File: xlineapi/src/lib.rs [hunk 1]
```diff
@@ -455,11 +455,6 @@ impl RequestWrapper {
     pub fn is_kv_request(&self) -> bool {
         self.backend() == RequestBackend::Kv
     }
-
-    /// Check if this request is a lease request
```
Comment (Phoenix500526) [inline xlineapi/src/lib.rs:459]: Why do we remove this method?

File: xline/src/server/command.rs [hunk 2]
```diff
@@ -408,29 +453,19 @@ impl ConflictCheck for Command {
...
-                RequestWrapper::LeaseRevokeRequest(ref req) => req.id,
-                _ => unreachable!("other request can not in this match"),
-            };
-            if lease_id1 == lease_id2 {
-                return true;
-            }
-        }
-
-        self.keys()
+        let lease_conflict = lease_ids_1
```
Comment (Phoenix500526) [inline xline/src/server/command.rs:459]: It looks like you want to conclude whether the `lease_ids_1` and the `lease_ids_2` are disjointed. We can use  HashSet and is_disjoint to do the same thing.

**Review by Phoenix500526 — COMMENTED** [review]
Plz describe the root cause of the relevant issue.

File: xline/src/server/command.rs [hunk 3]
```diff
@@ -388,6 +389,50 @@ pub struct Command {
     id: ProposeId,
 }
 
+/// get all lease ids in the request warapper
```
Comment (bsbds) [inline xline/src/server/command.rs:392]: There's a typo in the word "warapper"

File: xlineapi/src/lib.rs (hunk 1 above)
Comment (themanforfree) [reply xlineapi/src/lib.rs:459]: Because we only check lease request's lease id before, so we need this method to check whether it is a Lease request, but now we will check all the request‘s lease ID, not just the lease request.

File: xline/src/server/command.rs (hunk 2 above)
Comment (themanforfree) [reply xline/src/server/command.rs:459]: Fixed

File: xline/src/server/command.rs [hunk 4]
```diff
@@ -388,6 +389,50 @@ pub struct Command {
...
+fn get_lease_ids(wrapper: &RequestWrapper) -> Vec<i64> {
+    #[allow(clippy::wildcard_enum_match_arm)]
```
[the remark this answers is not in the document]
Comment (themanforfree) [reply xline/src/server/command.rs:394]: Fixed

File: xline/src/server/command.rs [hunk 5]
```diff
@@ -388,6 +389,50 @@ pub struct Command {
...
+    match *wrapper {
+        RequestWrapper::LeaseGrantRequest(ref req) => vec![req.id],
+        RequestWrapper::LeaseRevokeRequest(ref req) => vec![req.id],
```
[the remark this answers is not in the document]
Comment (themanforfree) [reply xline/src/server/command.rs]: This two reqs have different type, so they can't be merged

**Review by rogercloud — DISMISSED** [review]

**Review by Phoenix500526 — APPROVED** [review]

**Review by rogercloud — APPROVED** [review]

**Review by rogercloud — APPROVED** [review]
